In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings('ignore')

import os

In [76]:
csvs = os.listdir('Data/datasets_pub')

In [78]:
col_map_dict = {'labour_force_status': {1:'Employed, at work', 2: 'Employed, absent from work', 
        3: 'Unemployed', 4: 'Not in labour force'}, 
 'province':{10: 'Newfoundland and Labrador', 11: 'Prince Edward Island', 12: 'Nova Scotia', 13: 'New Brunswick', 
        24: 'Quebec', 35: 'Ontario', 46: 'Manitoba', 47: 'Saskatchewan', 48: 'Alberta', 59: 'British Columbia'}, 
 'nine_largest_cmas': {1: 'Québec', 2: 'Montréal', 3: 'Ottawa (Ontario part)', 4: 'Toronto', 5: 'Hamilton', 
        6: 'Winnipeg', 7: 'Calgary', 8: 'Edmonton', 9: 'Vancouver', 0: 'Other CMA or non-CMA'},
 'five_year_age_group': {1: '15 to 19 years',2: '20 to 24 years',3: '25 to 29 years',
        4: '30 to 34 years',5: '35 to 39 years',6: '40 to 44 years',7: '45 to 49 years', 8: '50 to 54 years', 
        9: '55 to 59 years',10: '60 to 64 years',11: '65 to 69 years', 12: '70 and over'}, 
 'age_group_15_29': {1: '15 to 16 years', 2: '17 to 19 years',3: '20 to 21 years', 4: '22 to 24 years',
        5: '25 to 26 years', 6: '27 to 29 years'}, 
 'sex': {1:'Male', 2:'Female'}, 
 'marital_status': {1: 'Married', 2: 'Living in common-law', 3: 'Widowed', 4: 'Separated', 5: 'Divorced', 
        6: 'Single, never married'},
 'highest_educational_attainment': {0: '0 to 8 years', 1: 'Some high school', 2: 'High school graduate', 
        3: 'Some postsecondary', 4: 'Postsecondary certificate or diploma', 5: "Bachelor's degree", 6: "Above bachelor's degree"}, 
 'single_or_multiple_jobholder': {1.:'Single', 2.:'Multiple'},
 'person_has_worked_in_last_year': {1.: 'Yes, within last year', 2.: 'Yes, more than 1 year ago', 3.: 'No, never worked'}, 
 'full_or_part_time_last_job': {1.:'Full-time (30 hours or more)', 2.:'Part-time'},
 'class_of_worker_main_job': {1: 'Public sector employees', 2: 'Private sector employees', 
         3: 'Self-employed incorporated, with paid help', 4: 'Self-employed incorporated, no paid help',
         5: 'Self-employed unincorporated, with paid help', 6: 'Self-employed unincorporated, no paid help',
         7: 'Unpaid family worker'},
 'immigrant_status': {1:'Immigrant, less than 10 years in Canada', 2:'Immigrant, more than 10 years in Canada', 
         3:'Non-immigrant'}, 
 'industry_of_main_job': {1: 'Agriculture', 2: 'Forestry and logging and support activities for forestry',
        3: 'Fishing, hunting and trapping', 4: 'Mining, quarrying, and oil and gas extraction',5: 'Utilities', 
        6: 'Construction', 7: 'Manufacturing - durable goods',8: 'Manufacturing - non-durable goods',
        9: 'Wholesale trade', 10: 'Retail trade', 11: 'Transportation and warehousing', 12: 'Finance and insurance',
        13: 'Real estate and rental and leasing',14: 'Professional, scientific and technical services',
        15: 'Business, building and other support services', 16: 'Educational services',
        17: 'Health care and social assistance', 18: 'Information, culture and recreation',
        19: 'Accommodation and food services', 20: 'Other services (except public administration)', 
        21: 'Public administration'},
 'occupation_at_main_job_col1': {1: 'Management occupations', 
        2: 'Business, finance and administration occupations, except management',
        3: 'Natural and applied sciences and related occupations, except management',
        4: 'Health occupations, except management',
        5: 'Occupations in education, law and social, community and government services, except management',
        6: 'Occupations in art, culture, recreation and sport, except management',
        7: 'Sales and service occupations, except management',
        8: 'Trades, transport and equipment operators and related occupations, except management',
        9: 'Natural resources, agriculture and related production occupations, except management',
       10: 'Occupations in manufacturing and utilities, except management'}, 
 'occupation_at_main_job_col2': {1: 'Legislative and senior management occupations',  
        2: 'Specialized middle management occupations', 
        3: 'Middle management occupations in retail and wholesale trade and customer services',
        4: 'Middle management occupations in trades, transportation, production and utilities',
        5: 'Professional occupations in finance', 6: 'Professional occupations in business',
        7: 'Administrative and financial supervisors and specialized administrative occupations',
        8: 'Administrative occupations and transportation logistics occupations',
        9: 'Administrative and financial support and supply chain logistics occupations',
        10: 'Professional occupations in natural sciences',
        11: 'Professional occupations in applied sciences (except engineering)',
        12: 'Professional occupations in engineering', 13: 'Technical occupations related to natural and applied sciences',
        14: 'Health treating and consultation services professionals',
        15: 'Therapy and assessment professionals', 16: 'Nursing and allied health professionals',
        17: 'Technical occupations in health', 18: 'Assisting occupations in support of health services',
        19: 'Professional occupations in law', 20: 'Professional occupations in education services',
        21: 'Professional occupations in social and community services', 22: 'Professional occupations in government services',
        23: 'Occupations in front-line public protection services',
        24: 'Paraprofessional occupations in legal, social, community and education services',
        25: 'Assisting occupations in education and in legal and public protection',
        26: 'Care providers and public protection support occupations and student monitors, crossing guards and related occupations',
        27: 'Professional occupations in art and culture', 28: 'Technical occupations in art, culture and sport',
        29: 'Occupations in art, culture and sport', 30: 'Support occupations in art, culture and sport',
        31: 'Retail sales and service supervisors and specialized occupations in sales and services',
        32: 'Occupations in sales and services', 
        33: 'Sales and service representatives and other customer and personal services occupations',
        34: 'Sales and service support occupations', 35: 'Technical trades and transportation officers and controllers',
        36: 'General trades', 
        37: 'Mail and message distribution, other transport equipment operators and related maintenance workers',
        38: 'Helpers and labourers and other transport drivers, operators and labourers',
        39: 'Supervisors and occupations in natural resources, agriculture and related production',
        40: 'Workers and labourers in natural resources, agriculture and related production',
        41: 'Supervisors, central control and process operators in processing, manufacturing and utilities and aircraft assemblers and inspectors',
        42: 'Machine operators, assemblers and inspectors in processing, manufacturing and printing',
        43: 'Labourers in processing, manufacturing and utilities'},
 'reason_of_absence_full_week': {0: 'Other reasons', 1: 'Own illness or disability', 
         2: 'Personal or family responsibilities', 3: 'Vacation'}, 
 'paid_for_time_off_full_week_absence': {1.:'Yes', 2.:'No'},
 'full_or_part_time_main_job': {1:'full_time', 2:'part_time'}, 
 'reason_for_part_week_absence': {0: 'Other reasons', 1: 'Own illness or disability', 
        2: 'Personal or family responsibilities', 3: 'Vacation or civic holiday', 4: 'Working short-time'},
 'reason_for_part_time_work': {0: 'Other reasons', 1: 'Own illness or disability', 2: 'Caring for children',
         3: 'Other personal or family responsibilities', 4: 'Going to school', 5: 'Personal preference',
         6: 'Business conditions or could not find full-time work, looked for full-time work in last month',
         7: 'Business conditions or could not find full-time work, did not look for full-time work in last month'},
 'union_status': {1: 'Union member', 2: 'Not a member but covered by a union contract or collective agreement',
         3: 'Non-unionized'}, 
 'job_permanency': {1: 'Permanent',2: 'Temporary, seasonal job',3: 'Temporary, term or contract job',
         4: 'Temporary, casual or other temporary jobs'},
 'establishment_size': {1: 'Less than 20 employees', 2: '20 to 99 employees', 3: '100 to 500 employees',
         4: 'More than 500 employees'}, 
 'firm_size': {1: 'Less than 20 employees', 2: '20 to 99 employees', 3: '100 to 500 employees',
         4: 'More than 500 employees'}, 
 'flows_into_unemployment': {1: 'Job losers, temporary layoff', 2: 'Job losers, permanent layoff', 3: 'Job leavers', 
        4: 'Job leavers/losers (status unknown), worked more than 1 year ago ', 5: 'New entrants', 
        6: 'Re-entrants, worked 1 year ago or less', 7: 'Re-entrants, worked more than 1 year ago', 8: 'Future starts'},
 'job_seekers_by_type_of_work_sought_and_temporary_layoffs_by_work_status_of_last_job': {1: 'Full-time', 
         2: 'Part-time', 3: 'Future starts'},
 'reason_for_leaving_job_previous_year_col1': {0: 'Job leavers, other reasons', 1: 'Job leavers, own illness or disability', 
        2: 'Job leavers, personal or family responsibilities', 3: 'Job leavers, going to school', 
        4: 'Job losers, laid off', 5: 'Job leavers, retired'},
 'reason_for_leaving_job_previous_year_col2': {0: 'Job leavers, other reasons', 1: 'Job leavers, own illness or disability', 
        2: 'Job leavers, caring for children', 3: 'Job leavers, pregnancy', 
        4: 'Job leavers, personal or family responsibilities', 5: 'Job leavers, going to school', 
        6: 'Job leavers, dissatisfied', 7: 'Job leavers, retired', 
        8: 'Job leavers, business sold or closed down (self-employed)', 9: 'Job losers, end of seasonal job (employee)', 
        10: 'Job losers, end of temporary or casual (employee)', 11: 'Job losers, company moved or out of business (employee)', 
        12: 'Job losers, business conditions (employee)', 13: 'Job losers, dismissal or other reasons'}, 
 'availability_during_reference_week': {1: 'Not available', 2: 'Yes, available'},
 'main_activity_before_started_looking_for_work': {0: 'Other', 1: 'Working', 2: 'Managing a home',  3: 'Going to school'},
 'reason_for_not_looking_for_work_during_the_reference_week': {0: 'Wanted work, reason - other',
         1: 'Wanted work, reason - own illness or disability', 2: 'Wanted work, reason - caring for children',
         3: 'Wanted work, reason - other personal or family responsibilities', 4: 'Wanted work, reason - school',
         5: 'Wanted work, reason - awaiting recall or reply', 6: 'Wanted work, reason - discouraged'},
 'temporary_layoff,_looked_for_work_during_the_last_four_weeks': {1:'Yes', 2:'No'},
 'current_student_status': {1: 'Non-student', 2: 'Full-time student', 3: 'Part-time student'}, 
 'type_of_economic_family': {1: 'Person not in an economic family', 2: 'Dual-earner couple, no children or none under 25',
        3: 'Dual-earner couple, youngest child 0 to 17', 4: 'Dual-earner couple, youngest child 18 to 24',
        5: 'Single-earner couple, male employed, no children or none under 25', 
        6: 'Single-earner couple, male employed, youngest child 0 to 17',
        7: 'Single-earner couple, male employed, youngest child 18 to 24',
        8: 'Single-earner couple, female employed, no children or none under 25',
        9: 'Single-earner couple, female employed, youngest child 0 to 17',
        10: 'Single-earner couple, female employed, youngest child 18 to 24',
        11: 'Non-earner couple, no children or none under 25', 12: 'Non-earner couple, youngest child 0 to 17',
        13: 'Non-earner couple, youngest child 18 to 24', 14: 'Lone-parent family, parent employed, youngest child 0 to 17',
        15: 'Lone-parent family, parent employed, youngest child 18 to 24', 
        16: 'Lone-parent family, parent not employed, youngest child 0 to 17',
        17: 'Lone-parent family, parent not employed, youngest child 18 to 24', 18: 'Other families'},
 'age_of_youngest_child': {1: 'Youngest child less than 6 years', 2: 'Youngest child 6 to 12 years',
            3: 'Youngest child 13 to 17 years', 4: 'Youngest child 18 to 24 years'}
}

cols_to_divide_by_ten = ['usual_hours_worked_per_week_at_main_job', 'actual_hours_worked_per_week_at_main_job',
    'usual_hours_worked_per_week_all_jobs', 'actual_hours_worked_per_week_all_jobs', 'hours_away_from_work_part_week_absence',
    'paid_overtime_hours_in_reference_week', 'unpaid_overtime_hours_in_reference_week',
    'number_of_overtime_or_extra_hours_worked']



def clean_df(df):
    df.columns = ['record_order', 'survey_year', 'survey_month', 'labour_force_status', 'province', 'nine_largest_cmas', 
            'five_year_age_group', 'age_group_15_29', 'sex', 'marital_status', 'highest_educational_attainment', 
            'single_or_multiple_jobholder', 'person_has_worked_in_last_year', 'full_or_part_time_last_job', 
            'class_of_worker_main_job', 'immigrant_status', 'industry_of_main_job', 'occupation_at_main_job_col1', 
            'occupation_at_main_job_col2', 'reason_of_absence_full_week', 'number_of_weeks_absent_from_work', 
            'paid_for_time_off_full_week_absence',  'usual_hours_worked_per_week_at_main_job', 
            'actual_hours_worked_per_week_at_main_job', 'full_or_part_time_main_job', 'usual_hours_worked_per_week_all_jobs', 
            'actual_hours_worked_per_week_all_jobs', 'hours_away_from_work_part_week_absence', 'reason_for_part_week_absence', 
            'paid_overtime_hours_in_reference_week', 'unpaid_overtime_hours_in_reference_week', 
            'number_of_overtime_or_extra_hours_worked', 'reason_for_part_time_work', 
            'job_tenure_months_current_employer', 'job_tenure_previous_employer', 'usual_hourly_wages', 'union_status', 
            'job_permanency', 'establishment_size', 'firm_size', 'duration_of_unemployment_weeks', 'flows_into_unemployment', 
            'job_seekers_by_type_of_work_sought_and_temporary_layoffs_by_work_status_of_last_job', 
            'reason_for_leaving_job_previous_year_col1', 'reason_for_leaving_job_previous_year_col2', 
            'duration_of_joblessness_months', 'availability_during_reference_week', 'unemployed,_used_public_employment_agency',
            'unemployed,_checked_with_employers_directly', 'unemployed,_checked_with_friends_or_relatives', 
            'unemployed,_looked_at_job_ads', 'unemployed,_placed_or_answered_ads', 'unemployed,_other_methods', 
            'main_activity_before_started_looking_for_work', 'reason_for_not_looking_for_work_during_the_reference_week', 
            'temporary_layoff,_looked_for_work_during_the_last_four_weeks', 'current_student_status', 'type_of_economic_family',
            'age_of_youngest_child', 'standard_final_weight']
    df.drop(columns = ['record_order'], inplace=True)
    year_month = [datetime.date(df['survey_year'].values[i], df['survey_month'].values[i], 1) for i in range(len(df))]
    df.insert(2, 'year_month', year_month)
    for col in df:
        if 'hours' in col:
            df[col] = df[col]/10
    df['usual_hourly_wages'] = df['usual_hourly_wages']/100
    df_numeric = df.copy()
    for col in df:
        if col in col_map_dict.keys():
            df[col] = df[col].map(col_map_dict[col])
    df_nulls = df.copy()     
    cat_columns = df.columns[list(df.dtypes == 'object')]
    num_columns = df.columns[list(df.dtypes != 'object')]
    for col in df.columns:
        if col in num_columns:
            df[col] = df[col].fillna(0)
    for col in df.columns:
        if col in cat_columns:
            df[col] = df[col].fillna('N_A')
    employed = df[(df['labour_force_status']=='Employed, at work')|(df['labour_force_status']=='Employed, absent from work')]
    num_columns = employed.columns[list(employed.dtypes != 'object')]          
    cols_to_remove = []
    for col in num_columns:
        if sum(employed[col])==0.0:
            cols_to_remove.append(col)            
    employed.drop(columns=cols_to_remove, inplace=True)
    cols_to_remove = []
    for col in employed.columns:
        a = employed[col].to_numpy()
        if a[0] == 'N_A':
            if (a[0] == a).all():
                cols_to_remove.append(col)
    employed.drop(columns=cols_to_remove, inplace=True)
    employed['short_term_absence'] = employed['hours_away_from_work_part_week_absence'].map(lambda x: 1 if x>0 else 0)
    employed['long_term_absence'] = employed['number_of_weeks_absent_from_work'].map(lambda x: 1 if x>0 else 0)
    #return df, employed, df_numeric, df_nulls
    return employed

In [79]:
df_dict = {}
# counter para ver como va el proceso (es muy lento)
counter = 0
for csv in csvs:
    emp = clean_df(pd.read_csv('Data/datasets_pub/'+csv))
    df_dict[csv[:-4]] = emp
    print(counter)
    counter += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47

In [81]:
df0120 = df_dict['pub0120']

merged_df = pd.DataFrame(columns=df0120.columns)

for key in df_dict.keys():
    merged_df = pd.concat([merged_df, df_dict[key]])
    
merged_df = merged_df.reset_index(drop=True)

In [82]:
merged_df.sample()

,survey_year,survey_month,year_month,labour_force_status,province,nine_largest_cmas,five_year_age_group,age_group_15_29,sex,marital_status,highest_educational_attainment,single_or_multiple_jobholder,class_of_worker_main_job,immigrant_status,industry_of_main_job,occupation_at_main_job_col1,occupation_at_main_job_col2,reason_of_absence_full_week,number_of_weeks_absent_from_work,paid_for_time_off_full_week_absence,usual_hours_worked_per_week_at_main_job,actual_hours_worked_per_week_at_main_job,full_or_part_time_main_job,usual_hours_worked_per_week_all_jobs,actual_hours_worked_per_week_all_jobs,hours_away_from_work_part_week_absence,reason_for_part_week_absence,paid_overtime_hours_in_reference_week,unpaid_overtime_hours_in_reference_week,number_of_overtime_or_extra_hours_worked,reason_for_part_time_work,job_tenure_months_current_employer,usual_hourly_wages,union_status,job_permanency,establishment_size,firm_size,current_student_status,type_of_economic_family,age_of_youngest_child,standard_final_weight,short_term_absence,long_term_absence
94852,2021,1,2021-01-01,"Employed, at work",Alberta,Other CMA or non-CMA,45 to 49 years,N_A,Male,Married,Above bachelor's degree,Single,Private sector employees,"Immigrant, more than 10 years in Canada","Mining, quarrying, and oil and gas extraction",Natural and applied sciences and related occup...,Professional occupations in engineering,N_A,0.0,N_A,40.0,44.0,full_time,40.0,44.0,0.0,N_A,0.0,4.0,4.0,N_A,136.0,75.0,Non-unionized,Permanent,More than 500 employees,More than 500 employees,Non-student,"Dual-earner couple, youngest child 0 to 17",Youngest child 13 to 17 years,77,0,0

In [84]:
def add_int_columns(df):
    age_group_int = df['five_year_age_group'].map(lambda x: int(x[:2]))
    df['age_group_int'] = age_group_int

    age_group_under_30_int = df['age_group_15_29'].map(lambda x: x.replace('N_A', '30'))
    age_group_under_30_int = age_group_under_30_int.map(lambda x: int(x[:2]))

    df['age_group_under_30_int'] = age_group_under_30_int

    df['firm_size_int']=df.firm_size.map({'More than 500 employees':501, '100 to 500 employees': 300, '20 to 99 employees': 50, 
                  'Less than 20 employees': 10, 'N_A':0})

    df['est_size_int']=df.establishment_size.map({'More than 500 employees':501, '100 to 500 employees': 300, 
                '20 to 99 employees': 50, 'Less than 20 employees': 10, 'N_A':0})

    df['age_youngest_child_int'] = df['age_of_youngest_child'].map({'N_A':0,
       'Youngest child less than 6 years':6, 'Youngest child 6 to 12 years':12, 
      'Youngest child 13 to 17 years':17,  'Youngest child 18 to 24 years':24})
    return df

merged_df = add_int_columns(merged_df)

In [85]:
merged_df.sample()

,survey_year,survey_month,year_month,labour_force_status,province,nine_largest_cmas,five_year_age_group,age_group_15_29,sex,marital_status,highest_educational_attainment,single_or_multiple_jobholder,class_of_worker_main_job,immigrant_status,industry_of_main_job,occupation_at_main_job_col1,occupation_at_main_job_col2,reason_of_absence_full_week,number_of_weeks_absent_from_work,paid_for_time_off_full_week_absence,usual_hours_worked_per_week_at_main_job,actual_hours_worked_per_week_at_main_job,full_or_part_time_main_job,usual_hours_worked_per_week_all_jobs,actual_hours_worked_per_week_all_jobs,hours_away_from_work_part_week_absence,reason_for_part_week_absence,paid_overtime_hours_in_reference_week,unpaid_overtime_hours_in_reference_week,number_of_overtime_or_extra_hours_worked,reason_for_part_time_work,job_tenure_months_current_employer,usual_hourly_wages,union_status,job_permanency,establishment_size,firm_size,current_student_status,type_of_economic_family,age_of_youngest_child,standard_final_weight,short_term_absence,long_term_absence,age_group_int,age_group_under_30_int,firm_size_int,est_size_int,age_youngest_child_int
313982,2021,2,2021-02-01,"Employed, at work",British Columbia,Other CMA or non-CMA,50 to 54 years,N_A,Male,Married,Above bachelor's degree,Single,Public sector employees,Non-immigrant,Public administration,Management occupations,Specialized middle management occupations,N_A,0.0,N_A,45.0,45.0,full_time,45.0,45.0,0.0,N_A,0.0,0.0,0.0,N_A,108.0,66.24,Non-unionized,Permanent,100 to 500 employees,100 to 500 employees,Non-student,"Dual-earner couple, youngest child 0 to 17",Youngest child 13 to 17 years,484,0,0,50,30,300,300,17

In [ ]:
merged_df[merged_df]

In [90]:
long_term_absence = merged_df[(merged_df.long_term_absence==1)&(merged_df.short_term_absence==0)]
short_term_absence = merged_df[(merged_df.short_term_absence==1)&(merged_df.long_term_absence==0)]
long_and_short_term = merged_df[(merged_df.short_term_absence==1)&(merged_df.long_term_absence==1)]

In [102]:
merged_df = merged_df[~((merged_df.short_term_absence==1)&(merged_df.long_term_absence==1))]
merged_df.reset_index(drop=True, inplace=True)

In [103]:
len(merged_df)

2704145

In [104]:
merged_df.to_csv('Data/clean_dfs/merged_employed.csv', index=False)

In [91]:
# Check that everything is good
short_term_absence.reason_of_absence_full_week.value_counts(), short_term_absence.labour_force_status.value_counts()

(reason_of_absence_full_week
 N_A    352639
 Name: count, dtype: int64,
 labour_force_status
 Employed, at work    352639
 Name: count, dtype: int64)

In [93]:
long_term_absence.drop(columns = ['labour_force_status', 'hours_away_from_work_part_week_absence',
                       'reason_for_part_week_absence','short_term_absence','long_term_absence'], inplace=True)
short_term_absence.drop(columns = ['labour_force_status', 'reason_of_absence_full_week', 
                    'number_of_weeks_absent_from_work', 'paid_for_time_off_full_week_absence', 'short_term_absence',
                                   'long_term_absence'], inplace=True)

In [ ]:
#year_month = [datetime.date(long_term_absence['survey_year'].values[i], long_term_absence['survey_month'].values[i], 1) for i in range(len(long_term_absence))]
#long_term_absence.insert(2, 'year_month', year_month)

In [ ]:
#year_month = [datetime.date(short_term_absence['survey_year'].values[i], short_term_absence['survey_month'].values[i], 1) for i in range(len(short_term_absence))]
#short_term_absence.insert(2, 'year_month', year_month)

In [94]:
long_term_absence.to_csv('Data/clean_dfs/long_absence.csv', index=False)
short_term_absence.to_csv('Data/clean_dfs/short_absence.csv', index=False)

In [65]:
def clean_df_numeric(df):
    df.columns = ['record_order', 'survey_year', 'survey_month', 'labour_force_status', 'province', 'nine_largest_cmas', 
            'five_year_age_group', 'age_group_15_29', 'sex', 'marital_status', 'highest_educational_attainment', 
            'single_or_multiple_jobholder', 'person_has_worked_in_last_year', 'full_or_part_time_last_job', 
            'class_of_worker_main_job', 'immigrant_status', 'industry_of_main_job', 'occupation_at_main_job_col1', 
            'occupation_at_main_job_col2', 'reason_of_absence_full_week', 'number_of_weeks_absent_from_work', 
            'paid_for_time_off_full_week_absence',  'usual_hours_worked_per_week_at_main_job', 
            'actual_hours_worked_per_week_at_main_job', 'full_or_part_time_main_job', 'usual_hours_worked_per_week_all_jobs', 
            'actual_hours_worked_per_week_all_jobs', 'hours_away_from_work_part_week_absence', 'reason_for_part_week_absence', 
            'paid_overtime_hours_in_reference_week', 'unpaid_overtime_hours_in_reference_week', 
            'number_of_overtime_or_extra_hours_worked', 'reason_for_part_time_work', 
            'job_tenure_months_current_employer', 'job_tenure_previous_employer', 'usual_hourly_wages', 'union_status', 
            'job_permanency', 'establishment_size', 'firm_size', 'duration_of_unemployment_weeks', 'flows_into_unemployment', 
            'job_seekers_by_type_of_work_sought_and_temporary_layoffs_by_work_status_of_last_job', 
            'reason_for_leaving_job_previous_year_col1', 'reason_for_leaving_job_previous_year_col2', 
            'duration_of_joblessness_months', 'availability_during_reference_week', 'unemployed,_used_public_employment_agency',
            'unemployed,_checked_with_employers_directly', 'unemployed,_checked_with_friends_or_relatives', 
            'unemployed,_looked_at_job_ads', 'unemployed,_placed_or_answered_ads', 'unemployed,_other_methods', 
            'main_activity_before_started_looking_for_work', 'reason_for_not_looking_for_work_during_the_reference_week', 
            'temporary_layoff,_looked_for_work_during_the_last_four_weeks', 'current_student_status', 'type_of_economic_family',
            'age_of_youngest_child', 'standard_final_weight']
    df.drop(columns = ['record_order'], inplace=True) #, 'survey_year', 'survey_month'], inplace=True)
    for col in df.columns:
        if 'hours' in col:
            df[col] = df[col]/10
    df['usual_hourly_wages'] = df['usual_hourly_wages']/100
    employed = df[(df['labour_force_status']==1)|(df['labour_force_status']==2)]       
    for col in employed.columns:
        if employed[col].isnull().sum()>0:
            employed[col] = employed[col] + 1
    cols_to_remove = []
    for col in df.columns:
        if sum(employed[col])==0.0:
            cols_to_remove.append(col)            
    employed.drop(columns=cols_to_remove, inplace=True)
    employed.fillna(0, inplace=True)
    year_month = [datetime.date(employed['survey_year'].values[i], employed['survey_month'].values[i], 1) for i in range(len(employed))]
    employed.insert(2, 'year_month', year_month)
    return employed

In [66]:
numeric_df_dict = {}
# counter para ver como va el proceso (es muy lento)
counter = 0
for csv in csvs:
    emp = clean_df_numeric(pd.read_csv('Data/datasets_pub/'+csv))
    numeric_df_dict[csv[:-4]] = emp
    print(counter)
    counter += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47

In [70]:
df0120 = numeric_df_dict['pub0120']

merged_num_df = pd.DataFrame(columns=df0120.columns)

for key in numeric_df_dict.keys():
    merged_num_df = pd.concat([merged_num_df, numeric_df_dict[key]])
    
merged_num_df = merged_num_df.reset_index(drop=True)

In [88]:
merged_num_df['short_term_absence'] = merged_num_df['hours_away_from_work_part_week_absence'].map(lambda x: 1 if x>0 else 0)
merged_num_df['long_term_absence'] = merged_num_df['number_of_weeks_absent_from_work'].map(lambda x: 1 if x>0 else 0)

In [89]:
merged_num_df.sample(10)

,survey_year,survey_month,year_month,labour_force_status,province,nine_largest_cmas,five_year_age_group,age_group_15_29,sex,marital_status,highest_educational_attainment,single_or_multiple_jobholder,person_has_worked_in_last_year,full_or_part_time_last_job,class_of_worker_main_job,immigrant_status,industry_of_main_job,occupation_at_main_job_col1,occupation_at_main_job_col2,reason_of_absence_full_week,number_of_weeks_absent_from_work,paid_for_time_off_full_week_absence,usual_hours_worked_per_week_at_main_job,actual_hours_worked_per_week_at_main_job,full_or_part_time_main_job,usual_hours_worked_per_week_all_jobs,actual_hours_worked_per_week_all_jobs,hours_away_from_work_part_week_absence,reason_for_part_week_absence,paid_overtime_hours_in_reference_week,unpaid_overtime_hours_in_reference_week,number_of_overtime_or_extra_hours_worked,reason_for_part_time_work,job_tenure_months_current_employer,job_tenure_previous_employer,usual_hourly_wages,union_status,job_permanency,establishment_size,firm_size,duration_of_unemployment_weeks,flows_into_unemployment,job_seekers_by_type_of_work_sought_and_temporary_layoffs_by_work_status_of_last_job,reason_for_leaving_job_previous_year_col1,reason_for_leaving_job_previous_year_col2,duration_of_joblessness_months,availability_during_reference_week,"unemployed,_used_public_employment_agency","unemployed,_checked_with_employers_directly","unemployed,_checked_with_friends_or_relatives","unemployed,_looked_at_job_ads","unemployed,_placed_or_answered_ads","unemployed,_other_methods",main_activity_before_started_looking_for_work,reason_for_not_looking_for_work_during_the_reference_week,"temporary_layoff,_looked_for_work_during_the_last_four_weeks",current_student_status,type_of_economic_family,age_of_youngest_child,standard_final_weight,short_term_absence,long_term_absence
52030,2020,1,2020-01-01,1,24,0,8,0.0,1,6,3,1.0,0.0,0.0,4.0,3,1.0,1.0,4.0,0.0,0.0,0.0,70.0,70.0,1.0,70.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,18,0.0,319,0,0
600500,2022,3,2022-03-01,1,12,0,4,0.0,2,2,2,1.0,0.0,0.0,2.0,3,10.0,7.0,31.0,0.0,0.0,0.0,40.0,40.0,1.0,40.0,40.0,1.0,0.0,1.0,1.0,1.0,0.0,189.0,0.0,33.21,4.0,2.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3,2.0,174,1,0
1718145,2022,8,2022-08-01,1,35,5,3,7.0,2,1,5,1.0,0.0,0.0,2.0,3,14.0,3.0,13.0,0.0,0.0,0.0,40.0,43.0,1.0,40.0,43.0,1.0,0.0,1.0,4.0,4.0,0.0,8.0,0.0,26.00,4.0,2.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7,0.0,333,1,0
78493,2021,1,2021-01-01,1,11,0,2,5.0,1,6,4,1.0,0.0,0.0,2.0,3,15.0,7.0,33.0,0.0,0.0,0.0,37.5,37.5,1.0,37.5,37.5,1.0,0.0,1.0,1.0,1.0,0.0,25.0,0.0,14.00,4.0,2.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1,0.0,98,1,0
2015901,2023,9,2023-09-01,1,24,1,4,0.0,2,2,4,1.0,0.0,0.0,2.0,3,14.0,3.0,11.0,0.0,0.0,0.0,37.5,36.5,1.0,37.5,36.5,2.0,3.0,1.0,1.0,1.0,0.0,81.0,0.0,33.82,4.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2,0.0,548,1,0
1747269,2023,8,2023-08-01,1,48,7,11,0.0,2,1,2,1.0,0.0,0.0,6.0,3,14.0,2.0,7.0,0.0,0.0,0.0,8.0,6.0,2.0,8.0,6.0,0.0,0.0,0.0,0.0,0.0,6.0,240.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.0,590,0,0
498075,2020,3,2020-03-01,1,59,0,10,0.0,1,2,5,1.0,0.0,0.0,2.0,3,8.0,1.0,3.0,0.0,0.0,0.0,40.0,40.0,1.0,40.0,40.0,1.0,0.0,1.0,1.0,1.0,0.0,240.0,0.0,46.67,4.0,2.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2,0.0,167,1,0
2093283,2021,10,2021-10-01,1,35,0,6,0.0,2,1,5,1.0,0.0,0.0,1.0,2,17.0,4.0,17.0,0.0,0.0,0.0,36.0,36.0,1.0,36.0,36.0,1.0,0.0,1.0,1.0,1.0,0.0,12.0,0.0,32.00,2.0,2.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3,3.0,456,1,0
1201774,2021,6,2021-06-01,1,35,0,11,0.0,2,1,2,1.0,0.0,0.0,2.0,2,8.0,2.0,7.0,0.0,0.0,0.0,30.0,30.0,1.0,30.0,30.0,1.0,0.0,1.0,1.0,1.0,0.0,240.0,0.0,51.00,4.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.0,264,1,0
1501198,2022,7,2022-07-01,2,47,0,3,7.0,2,2,4,1.0,0.0,0.0,6.0,3,17.0,4.0,17.0,4.0,2.0,0.0,25.0,0.0,2.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2,0.0,128,0,1

In [105]:
merged_num_df = merged_df[~((merged_df.short_term_absence==1)&(merged_df.long_term_absence==1))]
merged_num_df.reset_index(drop=True, inplace=True)

In [106]:
len(merged_num_df)

2704145

In [107]:
merged_num_df.to_csv('Data/clean_dfs/merged_numeric_employed.csv', index=False)

In [108]:
long_term_absence_num = merged_num_df[(merged_df.long_term_absence==1)&(merged_df.short_term_absence==0)]
short_term_absence_num = merged_num_df[(merged_df.short_term_absence==1)&(merged_df.long_term_absence==0)]

In [109]:
long_term_absence.to_csv('Data/clean_dfs/long_absence_numeric.csv', index=False)
short_term_absence.to_csv('Data/clean_dfs/short_absence_numeric.csv', index=False)